server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000

influx:
  url: http://localhost:8083
  userName: sonat
  password: sonat
  database: sensor
